services:
  super-notes:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${SERVER_PORT:-8080}
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-super_notes}
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: