services:
  super-notes:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${SERVER_PORT:-8080}
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    env_file:
      - .env

